name: talknearn
description: "A new Flutter project for a social earning platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: 
  provider: ^6.1.1
  go_router: ^13.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_database: ^12.1.0
  intl: ^0.20.2
  cloud_firestore: ^6.1.0
  flutter_lints: 
  http:
  bloc: ^9.1.0
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
  uses-material-design: true
